# Generated by Django 5.2.1 on 2025-06-03 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(default='922be0fa95ea429f9280acf0f4e32ed2', max_length=32, unique=True, verbose_name='分享码')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='访问密码')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('accessed_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': '分享链接',
                'verbose_name_plural': '分享链接',
            },
        ),
    ]
