# Generated by Django 5.2.1 on 2025-06-03 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '作品分类',
                'verbose_name_plural': '作品分类',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='作品标题')),
                ('description', models.TextField(blank=True, verbose_name='作品描述')),
                ('image', models.ImageField(upload_to='works/%Y/%m/%d', verbose_name='作品图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shot_date', models.DateField(blank=True, null=True, verbose_name='拍摄日期')),
                ('camera_model', models.CharField(blank=True, max_length=100, verbose_name='相机型号')),
                ('is_public', models.BooleanField(default=False, verbose_name='公开显示')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='摄影师')),
            ],
            options={
                'verbose_name': '摄影作品',
                'verbose_name_plural': '摄影作品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关联时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.category', verbose_name='分类')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': '作品分类关联',
                'verbose_name_plural': '作品分类关联',
                'db_table': 'works_workcategory',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='categories',
            field=models.ManyToManyField(through='works.WorkCategory', to='works.category', verbose_name='作品分类'),
        ),
    ]
