# Generated by Django 5.2.3 on 2025-12-11 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='likes',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='点赞数'),
        ),
        migrations.CreateModel(
            name='WorkLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_like_records', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_records', to='works.work')),
            ],
            options={
                'db_table': 'works_worklike',
                'unique_together': {('work', 'user')},
            },
        ),
    ]
